# Generated by Django 2.2.4 on 2019-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='rol',
            field=models.CharField(choices=[('1', 'Aprendiz'), ('2', 'Vocero')], default='1', max_length=1),
        ),
    ]
